### ISSUE TITLE
./gen_daily_txt.sh is giving error

### ISSUE THREAD

**Issue by mohit92** [karthikraman/panchangam#5]
I am trying the following command and getting the error. Can you please help with what could be missing?

./gen_daily_txt.sh Ujjain 23:17:65 75:78:85 'Asia/Calcutta' 2020 devanagari 'hh:mm' lagna
Computing 2020 daily panchangam for Ujjain (23:17:65,75:78:85) - Asia/Calcutta in devanagari script...
***
DEBUG: 2019-09-14 13:40:37,055 {common.py:868}: {'DataSource': <class 'sanskrit_data.schema.common.DataSource'>, 'JsonObject': <class 'sanskrit_data.schema.common.JsonObject'>, 'JsonObjectNode': <class 'sanskrit_data.schema.common.JsonObjectNode'>, 'NamedEntity': <class 'sanskrit_data.schema.common.NamedEntity'>, 'SchemaError': <class 'jsonschema.exceptions.SchemaError'>, 'ScriptRendering': <class 'sanskrit_data.schema.common.ScriptRendering'>, 'Target': <class 'sanskrit_data.schema.common.Target'>, 'TargetValidationError': <class 'sanskrit_data.schema.common.TargetValidationError'>, 'Text': <class 'sanskrit_data.schema.common.Text'>, 'UllekhanamJsonObject': <class 'sanskrit_data.schema.common.UllekhanamJsonObject'>, 'ValidationError': <class 'jsonschema.exceptions.ValidationError'>}
No precomputed data available. Computing panchangam...
Writing computed panchangam to /Users/mohit/Documents/Ujjain-2020.json...
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.7/site-packages/jyotisha/panchangam/scripts/write_daily_panchangam_txt.py", line 395, in <module>
    main()
  File "/usr/local/lib/python3.7/site-packages/jyotisha/panchangam/scripts/write_daily_panchangam_txt.py", line 383, in main
    panchangam = jyotisha.panchangam.spatio_temporal.annual.get_panchangam(city=city, year=year, script=script, fmt=fmt, compute_lagnams=compute_lagnams)
  File "/usr/local/lib/python3.7/site-packages/jyotisha/panchangam/spatio_temporal/annual.py", line 1672, in get_panchangam
    panchangam.update_festival_details()
  File "/usr/local/lib/python3.7/site-packages/jyotisha/panchangam/spatio_temporal/annual.py", line 1625, in update_festival_details
    self.compute_festivals()
  File "/usr/local/lib/python3.7/site-packages/jyotisha/panchangam/spatio_temporal/annual.py", line 1073, in compute_festivals
    festival_rules = read_old_festival_rules_dict(os.path.join(CODE_ROOT, 'panchangam/temporal/festival/legacy/festival_rules.json'))
  File "/usr/local/lib/python3.7/site-packages/jyotisha/panchangam/temporal/festival/__init__.py", line 581, in read_old_festival_rules_dict
    with open(file_name, encoding="utf-8") as festivals_data:
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/lib/python3.7/site-packages/jyotisha/panchangam/temporal/festival/legacy/festival_rules.json'
error!

**Comment by karthikraman** [comment]
Can you clone the adyatithi github repo (
https://github.com/sanskrit-coders/adyatithi  ) into the
'/usr/local/lib/python3.7/site-packages/jyotisha/panchangam/temporal/festival/'
- not sure why it doesn't happen automatically...

**Comment by mohit92** [comment]
Yes it worked! Thanks :-)
