### ISSUE TITLE
Error after running ./gen_daily_cal.sh Chennai 13:05:24 80:16:12 'Asia/Calcutta' 2017 devanagari lagna

### ISSUE THREAD

**Issue by mihirsane** [karthikraman/panchangam#6]
```
{'DataSource': <class 'sanskrit_data.schema.common.DataSource'>, 'JsonObject': <class 'sanskrit_data.schema.common.JsonObject'>, 'JsonObjectNode': <class 'sanskrit_data.schema.common.JsonObjectNode'>, 'NamedEntity': <class 'sanskrit_data.schema.common.NamedEntity'>, 'SchemaError': <class 'jsonschema.exceptions.SchemaError'>, 'ScriptRendering': <class 'sanskrit_data.schema.common.ScriptRendering'>, 'Target': <class 'sanskrit_data.schema.common.Target'>, 'TargetValidationError': <class 'sanskrit_data.schema.common.TargetValidationError'>, 'Text': <class 'sanskrit_data.schema.common.Text'>, 'UllekhanamJsonObject': <class 'sanskrit_data.schema.common.UllekhanamJsonObject'>, 'ValidationError': <class 'jsonschema.exceptions.ValidationError'>} 
No precomputed data available. Computing panchangam...
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.8/site-packages/jyotisha/panchangam/scripts/write_daily_panchangam_tex.py", line 295, in <module>
    main()
  File "/usr/local/lib/python3.8/site-packages/jyotisha/panchangam/scripts/write_daily_panchangam_tex.py", line 283, in main
    panchangam = jyotisha.panchangam.spatio_temporal.annual.get_panchangam(city=city, year=year, script=script, fmt=fmt, compute_lagnams=compute_lagnams, ayanamsha_id=swe.SIDM_TRUE_CITRA)
  File "/usr/local/lib/python3.8/site-packages/jyotisha/panchangam/spatio_temporal/annual.py", line 31, in get_panchangam
    panchangam = periodical.Panchangam(city=city, start_date='%d-01-01' % year, end_date='%d-12-31' % year, script=script, fmt=fmt, compute_lagnams=compute_lagnams, ayanamsha_id=ayanamsha_id)
  File "/usr/local/lib/python3.8/site-packages/jyotisha/panchangam/spatio_temporal/periodical.py", line 54, in __init__
    self.add_details(compute_lagnams=compute_lagnams)
  File "/usr/local/lib/python3.8/site-packages/jyotisha/panchangam/spatio_temporal/periodical.py", line 1945, in add_details
    self.compute_angams(compute_lagnams=compute_lagnams)
  File "/usr/local/lib/python3.8/site-packages/jyotisha/panchangam/spatio_temporal/periodical.py", line 98, in compute_angams
    daily_panchangam_start = daily.DailyPanchanga(city=self.city, year=prev_day_yy, month=prev_day_mm, day=prev_day_dd, ayanamsha_id=self.ayanamsha_id)
  File "/usr/local/lib/python3.8/site-packages/jyotisha/panchangam/spatio_temporal/daily.py", line 48, in __init__
    self.compute_sun_moon_transitions(previous_day_panchangam=previous_day_panchangam)
  File "/usr/local/lib/python3.8/site-packages/jyotisha/panchangam/spatio_temporal/daily.py", line 120, in compute_sun_moon_transitions
    self.tithi_data = temporal.get_angam_data(self.jd_sunrise, self.jd_next_sunrise, temporal.TITHI, ayanamsha_id=self.ayanamsha_id)
  File "/usr/local/lib/python3.8/site-packages/jyotisha/panchangam/temporal/__init__.py", line 471, in get_angam_data
    angam_now = get_angam(jd_sunrise, angam_type, ayanamsha_id=ayanamsha_id)
  File "/usr/local/lib/python3.8/site-packages/jyotisha/panchangam/temporal/__init__.py", line 327, in get_angam
    return int(1 + floor(get_angam_float(jd, angam_type, ayanamsha_id=ayanamsha_id)))
  File "/usr/local/lib/python3.8/site-packages/jyotisha/panchangam/temporal/__init__.py", line 219, in get_angam_float
    lmoon = (swe.calc_ut(jd, swe.MOON)[0] - swe.get_ayanamsa(jd)) % 360
TypeError: unsupported operand type(s) for -: 'tuple' and 'float'

```

**Comment by karthikraman** [comment]
I think this is because of sanskrit-coders/jyotisha#40 -- you can use an older version of swisseph or fix the `calc_ut`. Will try to fix it as soon as possible

**Comment by mihirsane** [comment]
Will try an older version. But do let me know once you fix it. Thanks @karthikraman

**Comment by vvasuki** [comment]
> Will try an older version. But do let me know once you fix it. Thanks @karthikraman

`calc_ut` is fixed now - so, you either use latest version of both jyotisha and pyswisseph - or old versions of both.

**Comment by vvasuki** [comment]
But beware if using newer version - changes are not fully cjecked - https://github.com/sanskrit-coders/jyotisha/issues/44  . Perhaps you can help verify that all's well.
