### ISSUE TITLE
Error Running ./gen_monthly_cal.sh

### ISSUE THREAD

**Issue by funnymomo** [karthikraman/panchangam#8]
Hi... Good repo. Can you please help on why this error may be coming.

Using the following docker : 

```
FROM python:3.7

RUN apt-get -y update && apt-get -y install texlive-xetex  texlive-latex-extra texlive-fonts-extra nano mlocate

WORKDIR /src
RUN git clone https://github.com/karthikraman/panchangam.git
RUN cd panchangam/bin && pip install git+https://github.com/sanskrit-coders/jyotisha@master -U && pip install git+https://github.com/astrorigin/pyswisseph@master -U

WORKDIR /src/panchangam/bin
ENTRYPOINT ["bash"]

```

Ran : 
`./gen_monthly_cal.sh Chennai 13:05:24 80:16:12 'Asia/Calcutta' 2020 devanagari`

Get error

```
ERROR: 2020-11-28 04:20:03,580 {__init__.py:39}: Relative festival (bhAdrapada) mahAlaya amAvAsyA not in festival_id_to_days!
ERROR: 2020-11-28 04:20:03,582 {__init__.py:39}: Relative festival zayana-EkAdazI not in festival_id_to_days!
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.7/site-packages/jyotisha/panchaanga/writer/tex/write_monthly_panchaanga_tex.py", line 350, in <module>
    main()
  File "/usr/local/lib/python3.7/site-packages/jyotisha/panchaanga/writer/tex/write_monthly_panchaanga_tex.py", line 345, in main
    write_monthly_tex(panchaanga)
TypeError: write_monthly_tex() missing 1 required positional argument: 'template_file'
error!
```

Ls of some important directories

```
root@1eb682b46761:/src/panchangam/bin# ls -al  /usr/local/lib/python3.7/site-packages/jyotisha/panchaanga/temporal/festival/
total 36
drwxr-sr-x 6 root staff 4096 Nov 28 01:40 .
drwxr-sr-x 7 root staff 4096 Nov 28 01:40 ..
-rw-r--r-- 1 root staff 3982 Nov 28 01:40 __init__.py
drwxr-sr-x 2 root staff 4096 Nov 28 01:40 __pycache__
drwxr-sr-x 4 root staff 4096 Nov 28 01:40 applier
drwxr-sr-x 9 root staff 4096 Nov 28 01:40 data
-rw-r--r-- 1 root staff 6642 Nov 28 01:40 priority_decision.py
drwxr-sr-x 3 root staff 4096 Nov 28 01:40 rules
```

AND : ls -al /usr/local/lib/python3.7/site-packages/jyotisha/panchaanga/temporal/festival/data/
```
root@22771e1a4179:/src/panchangam/bin# ls -al /usr/local/lib/python3.7/site-packages/jyotisha/panchaanga/temporal/festival/data/
total 56
drwxr-sr-x  9 root staff 4096 Nov 28 04:33 .
drwxr-sr-x  6 root staff 4096 Nov 28 04:33 ..
-rw-r--r--  1 root staff   79 Nov 28 04:33 .git
-rw-r--r--  1 root staff 1203 Nov 28 04:33 .gitignore
-rw-r--r--  1 root staff 1089 Nov 28 04:33 LICENSE
-rw-r--r--  1 root staff 2249 Nov 28 04:33 README.md
drwxr-sr-x 14 root staff 4096 Nov 28 04:33 devatA
-rw-r--r--  1 root staff  645 Nov 28 04:33 festivals_to_be_verified.json
drwxr-sr-x  3 root staff 4096 Nov 28 04:33 gRhya
drwxr-sr-x  5 root staff 4096 Nov 28 04:33 general
drwxr-sr-x 12 root staff 4096 Nov 28 04:33 mahApuruSha
drwxr-sr-x  5 root staff 4096 Nov 28 04:33 tamil
drwxr-sr-x  8 root staff 4096 Nov 28 04:33 temples
drwxr-sr-x 10 root staff 4096 Nov 28 04:33 time_focus
```

**Comment by vvasuki** [comment]
See https://github.com/karthikraman/panchangam/issues/9#issuecomment-752547429
